/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package currencyconverter;

/**
 *
 * @author vishnuneem
 */
public class chooseCurrency extends javax.swing.JFrame {

    /**
     * Creates new form chooseCurrency
     */
    public chooseCurrency() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inrToUsd = new javax.swing.JLabel();
        usdToInr = new javax.swing.JLabel();
        jpyToInr = new javax.swing.JLabel();
        inrToJpy = new javax.swing.JLabel();
        inrToCny = new javax.swing.JLabel();
        cnyToInr = new javax.swing.JLabel();
        krwToInr = new javax.swing.JLabel();
        inrToKrw = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Choose the currency to convert");

        inrToUsd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        inrToUsd.setForeground(new java.awt.Color(0, 0, 0));
        inrToUsd.setText("INR TO USD");
        inrToUsd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inrToUsdMouseClicked(evt);
            }
        });

        usdToInr.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        usdToInr.setForeground(new java.awt.Color(0, 0, 0));
        usdToInr.setText("USD TO INR");
        usdToInr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usdToInrMouseClicked(evt);
            }
        });

        jpyToInr.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jpyToInr.setForeground(new java.awt.Color(0, 0, 0));
        jpyToInr.setText("JPY TO INR");
        jpyToInr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpyToInrMouseClicked(evt);
            }
        });

        inrToJpy.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        inrToJpy.setForeground(new java.awt.Color(0, 0, 0));
        inrToJpy.setText("INR TO JPY");
        inrToJpy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inrToJpyMouseClicked(evt);
            }
        });

        inrToCny.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        inrToCny.setForeground(new java.awt.Color(0, 0, 0));
        inrToCny.setText("INR TO CNY");
        inrToCny.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inrToCnyMouseClicked(evt);
            }
        });

        cnyToInr.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cnyToInr.setForeground(new java.awt.Color(0, 0, 0));
        cnyToInr.setText("CNY TO INR");
        cnyToInr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cnyToInrMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cnyToInrMouseEntered(evt);
            }
        });

        krwToInr.setBackground(new java.awt.Color(255, 255, 255));
        krwToInr.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        krwToInr.setForeground(new java.awt.Color(0, 0, 0));
        krwToInr.setText("KRW TO INR");
        krwToInr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                krwToInrMouseClicked(evt);
            }
        });

        inrToKrw.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        inrToKrw.setForeground(new java.awt.Color(0, 0, 0));
        inrToKrw.setText("INR TO KRW");
        inrToKrw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inrToKrwMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(krwToInr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inrToKrw))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cnyToInr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inrToCny))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jpyToInr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inrToJpy))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(usdToInr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inrToUsd))
                    .addComponent(jLabel1))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inrToUsd)
                    .addComponent(usdToInr))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpyToInr)
                    .addComponent(inrToJpy))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inrToCny)
                    .addComponent(cnyToInr))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(krwToInr)
                    .addComponent(inrToKrw))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usdToInrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usdToInrMouseClicked
        // TODO add your handling code here:
        USD_TO_INR i = new USD_TO_INR();
        i.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_usdToInrMouseClicked

    private void inrToUsdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inrToUsdMouseClicked
        // TODO add your handling code here:
        INR_TO_USD i = new INR_TO_USD();
        i.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_inrToUsdMouseClicked

    private void jpyToInrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpyToInrMouseClicked
        // TODO add your handling code here:
        JPY_TO_INR i = new JPY_TO_INR();
        i.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jpyToInrMouseClicked

    private void inrToJpyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inrToJpyMouseClicked
        // TODO add your handling code here:
        INR_TO_JPY i = new INR_TO_JPY();
        i.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_inrToJpyMouseClicked

    private void cnyToInrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnyToInrMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cnyToInrMouseEntered

    private void cnyToInrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnyToInrMouseClicked
        // TODO add your handling code here:
        CNY_TO_INR i = new CNY_TO_INR();
        i.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_cnyToInrMouseClicked

    private void inrToCnyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inrToCnyMouseClicked
        // TODO add your handling code here:
        INR_TO_CNY i = new INR_TO_CNY();
        i.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_inrToCnyMouseClicked

    private void krwToInrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_krwToInrMouseClicked
        // TODO add your handling code here:
        KRW_TO_INR i = new KRW_TO_INR();
        i.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_krwToInrMouseClicked

    private void inrToKrwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inrToKrwMouseClicked
        // TODO add your handling code here:
        INR_TO_KRW i = new INR_TO_KRW();
        i.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_inrToKrwMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chooseCurrency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chooseCurrency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chooseCurrency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chooseCurrency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chooseCurrency().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cnyToInr;
    private javax.swing.JLabel inrToCny;
    private javax.swing.JLabel inrToJpy;
    private javax.swing.JLabel inrToKrw;
    private javax.swing.JLabel inrToUsd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jpyToInr;
    private javax.swing.JLabel krwToInr;
    private javax.swing.JLabel usdToInr;
    // End of variables declaration//GEN-END:variables
}
